// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FkValueMap.proto

package com.alimin.fk.pb;

public final class FkValueMapOuterClass {
  private FkValueMapOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FkValueMapOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.alimin.fk.pb.FkValueMap)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, .com.alimin.fk.pb.FkPbValue&gt; value = 1;</code>
     */
    int getValueCount();
    /**
     * <code>map&lt;string, .com.alimin.fk.pb.FkPbValue&gt; value = 1;</code>
     */
    boolean containsValue(
        java.lang.String key);
    /**
     * Use {@link #getValueMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.alimin.fk.pb.FkPbValueOuterClass.FkPbValue>
    getValue();
    /**
     * <code>map&lt;string, .com.alimin.fk.pb.FkPbValue&gt; value = 1;</code>
     */
    java.util.Map<java.lang.String, com.alimin.fk.pb.FkPbValueOuterClass.FkPbValue>
    getValueMap();
    /**
     * <code>map&lt;string, .com.alimin.fk.pb.FkPbValue&gt; value = 1;</code>
     */

    com.alimin.fk.pb.FkPbValueOuterClass.FkPbValue getValueOrDefault(
        java.lang.String key,
        com.alimin.fk.pb.FkPbValueOuterClass.FkPbValue defaultValue);
    /**
     * <code>map&lt;string, .com.alimin.fk.pb.FkPbValue&gt; value = 1;</code>
     */

    com.alimin.fk.pb.FkPbValueOuterClass.FkPbValue getValueOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code com.alimin.fk.pb.FkValueMap}
   */
  public static final class FkValueMap extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.alimin.fk.pb.FkValueMap)
      FkValueMapOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FkValueMap.newBuilder() to construct.
    private FkValueMap(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FkValueMap() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FkValueMap();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FkValueMap(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                value_ = com.google.protobuf.MapField.newMapField(
                    ValueDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, com.alimin.fk.pb.FkPbValueOuterClass.FkPbValue>
              value__ = input.readMessage(
                  ValueDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              value_.getMutableMap().put(
                  value__.getKey(), value__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alimin.fk.pb.FkValueMapOuterClass.internal_static_com_alimin_fk_pb_FkValueMap_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetValue();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alimin.fk.pb.FkValueMapOuterClass.internal_static_com_alimin_fk_pb_FkValueMap_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alimin.fk.pb.FkValueMapOuterClass.FkValueMap.class, com.alimin.fk.pb.FkValueMapOuterClass.FkValueMap.Builder.class);
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    private static final class ValueDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.alimin.fk.pb.FkPbValueOuterClass.FkPbValue> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.alimin.fk.pb.FkPbValueOuterClass.FkPbValue>newDefaultInstance(
                  com.alimin.fk.pb.FkValueMapOuterClass.internal_static_com_alimin_fk_pb_FkValueMap_ValueEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.alimin.fk.pb.FkPbValueOuterClass.FkPbValue.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, com.alimin.fk.pb.FkPbValueOuterClass.FkPbValue> value_;
    private com.google.protobuf.MapField<java.lang.String, com.alimin.fk.pb.FkPbValueOuterClass.FkPbValue>
    internalGetValue() {
      if (value_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ValueDefaultEntryHolder.defaultEntry);
      }
      return value_;
    }

    public int getValueCount() {
      return internalGetValue().getMap().size();
    }
    /**
     * <code>map&lt;string, .com.alimin.fk.pb.FkPbValue&gt; value = 1;</code>
     */

    @java.lang.Override
    public boolean containsValue(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetValue().getMap().containsKey(key);
    }
    /**
     * Use {@link #getValueMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.alimin.fk.pb.FkPbValueOuterClass.FkPbValue> getValue() {
      return getValueMap();
    }
    /**
     * <code>map&lt;string, .com.alimin.fk.pb.FkPbValue&gt; value = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, com.alimin.fk.pb.FkPbValueOuterClass.FkPbValue> getValueMap() {
      return internalGetValue().getMap();
    }
    /**
     * <code>map&lt;string, .com.alimin.fk.pb.FkPbValue&gt; value = 1;</code>
     */
    @java.lang.Override

    public com.alimin.fk.pb.FkPbValueOuterClass.FkPbValue getValueOrDefault(
        java.lang.String key,
        com.alimin.fk.pb.FkPbValueOuterClass.FkPbValue defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.alimin.fk.pb.FkPbValueOuterClass.FkPbValue> map =
          internalGetValue().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .com.alimin.fk.pb.FkPbValue&gt; value = 1;</code>
     */
    @java.lang.Override

    public com.alimin.fk.pb.FkPbValueOuterClass.FkPbValue getValueOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.alimin.fk.pb.FkPbValueOuterClass.FkPbValue> map =
          internalGetValue().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetValue(),
          ValueDefaultEntryHolder.defaultEntry,
          1);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, com.alimin.fk.pb.FkPbValueOuterClass.FkPbValue> entry
           : internalGetValue().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.alimin.fk.pb.FkPbValueOuterClass.FkPbValue>
        value__ = ValueDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, value__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.alimin.fk.pb.FkValueMapOuterClass.FkValueMap)) {
        return super.equals(obj);
      }
      com.alimin.fk.pb.FkValueMapOuterClass.FkValueMap other = (com.alimin.fk.pb.FkValueMapOuterClass.FkValueMap) obj;

      if (!internalGetValue().equals(
          other.internalGetValue())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetValue().getMap().isEmpty()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + internalGetValue().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.alimin.fk.pb.FkValueMapOuterClass.FkValueMap parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alimin.fk.pb.FkValueMapOuterClass.FkValueMap parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alimin.fk.pb.FkValueMapOuterClass.FkValueMap parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alimin.fk.pb.FkValueMapOuterClass.FkValueMap parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alimin.fk.pb.FkValueMapOuterClass.FkValueMap parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alimin.fk.pb.FkValueMapOuterClass.FkValueMap parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alimin.fk.pb.FkValueMapOuterClass.FkValueMap parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.alimin.fk.pb.FkValueMapOuterClass.FkValueMap parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.alimin.fk.pb.FkValueMapOuterClass.FkValueMap parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.alimin.fk.pb.FkValueMapOuterClass.FkValueMap parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.alimin.fk.pb.FkValueMapOuterClass.FkValueMap parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.alimin.fk.pb.FkValueMapOuterClass.FkValueMap parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.alimin.fk.pb.FkValueMapOuterClass.FkValueMap prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.alimin.fk.pb.FkValueMap}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.alimin.fk.pb.FkValueMap)
        com.alimin.fk.pb.FkValueMapOuterClass.FkValueMapOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.alimin.fk.pb.FkValueMapOuterClass.internal_static_com_alimin_fk_pb_FkValueMap_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetValue();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableValue();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.alimin.fk.pb.FkValueMapOuterClass.internal_static_com_alimin_fk_pb_FkValueMap_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alimin.fk.pb.FkValueMapOuterClass.FkValueMap.class, com.alimin.fk.pb.FkValueMapOuterClass.FkValueMap.Builder.class);
      }

      // Construct using com.alimin.fk.pb.FkValueMapOuterClass.FkValueMap.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        internalGetMutableValue().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alimin.fk.pb.FkValueMapOuterClass.internal_static_com_alimin_fk_pb_FkValueMap_descriptor;
      }

      @java.lang.Override
      public com.alimin.fk.pb.FkValueMapOuterClass.FkValueMap getDefaultInstanceForType() {
        return com.alimin.fk.pb.FkValueMapOuterClass.FkValueMap.getDefaultInstance();
      }

      @java.lang.Override
      public com.alimin.fk.pb.FkValueMapOuterClass.FkValueMap build() {
        com.alimin.fk.pb.FkValueMapOuterClass.FkValueMap result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.alimin.fk.pb.FkValueMapOuterClass.FkValueMap buildPartial() {
        com.alimin.fk.pb.FkValueMapOuterClass.FkValueMap result = new com.alimin.fk.pb.FkValueMapOuterClass.FkValueMap(this);
        int from_bitField0_ = bitField0_;
        result.value_ = internalGetValue();
        result.value_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alimin.fk.pb.FkValueMapOuterClass.FkValueMap) {
          return mergeFrom((com.alimin.fk.pb.FkValueMapOuterClass.FkValueMap)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.alimin.fk.pb.FkValueMapOuterClass.FkValueMap other) {
        if (other == com.alimin.fk.pb.FkValueMapOuterClass.FkValueMap.getDefaultInstance()) return this;
        internalGetMutableValue().mergeFrom(
            other.internalGetValue());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.alimin.fk.pb.FkValueMapOuterClass.FkValueMap parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.alimin.fk.pb.FkValueMapOuterClass.FkValueMap) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, com.alimin.fk.pb.FkPbValueOuterClass.FkPbValue> value_;
      private com.google.protobuf.MapField<java.lang.String, com.alimin.fk.pb.FkPbValueOuterClass.FkPbValue>
      internalGetValue() {
        if (value_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ValueDefaultEntryHolder.defaultEntry);
        }
        return value_;
      }
      private com.google.protobuf.MapField<java.lang.String, com.alimin.fk.pb.FkPbValueOuterClass.FkPbValue>
      internalGetMutableValue() {
        onChanged();;
        if (value_ == null) {
          value_ = com.google.protobuf.MapField.newMapField(
              ValueDefaultEntryHolder.defaultEntry);
        }
        if (!value_.isMutable()) {
          value_ = value_.copy();
        }
        return value_;
      }

      public int getValueCount() {
        return internalGetValue().getMap().size();
      }
      /**
       * <code>map&lt;string, .com.alimin.fk.pb.FkPbValue&gt; value = 1;</code>
       */

      @java.lang.Override
      public boolean containsValue(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetValue().getMap().containsKey(key);
      }
      /**
       * Use {@link #getValueMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.alimin.fk.pb.FkPbValueOuterClass.FkPbValue> getValue() {
        return getValueMap();
      }
      /**
       * <code>map&lt;string, .com.alimin.fk.pb.FkPbValue&gt; value = 1;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, com.alimin.fk.pb.FkPbValueOuterClass.FkPbValue> getValueMap() {
        return internalGetValue().getMap();
      }
      /**
       * <code>map&lt;string, .com.alimin.fk.pb.FkPbValue&gt; value = 1;</code>
       */
      @java.lang.Override

      public com.alimin.fk.pb.FkPbValueOuterClass.FkPbValue getValueOrDefault(
          java.lang.String key,
          com.alimin.fk.pb.FkPbValueOuterClass.FkPbValue defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, com.alimin.fk.pb.FkPbValueOuterClass.FkPbValue> map =
            internalGetValue().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .com.alimin.fk.pb.FkPbValue&gt; value = 1;</code>
       */
      @java.lang.Override

      public com.alimin.fk.pb.FkPbValueOuterClass.FkPbValue getValueOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, com.alimin.fk.pb.FkPbValueOuterClass.FkPbValue> map =
            internalGetValue().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearValue() {
        internalGetMutableValue().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .com.alimin.fk.pb.FkPbValue&gt; value = 1;</code>
       */

      public Builder removeValue(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableValue().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.alimin.fk.pb.FkPbValueOuterClass.FkPbValue>
      getMutableValue() {
        return internalGetMutableValue().getMutableMap();
      }
      /**
       * <code>map&lt;string, .com.alimin.fk.pb.FkPbValue&gt; value = 1;</code>
       */
      public Builder putValue(
          java.lang.String key,
          com.alimin.fk.pb.FkPbValueOuterClass.FkPbValue value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) {
  throw new NullPointerException("map value");
}

        internalGetMutableValue().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .com.alimin.fk.pb.FkPbValue&gt; value = 1;</code>
       */

      public Builder putAllValue(
          java.util.Map<java.lang.String, com.alimin.fk.pb.FkPbValueOuterClass.FkPbValue> values) {
        internalGetMutableValue().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.alimin.fk.pb.FkValueMap)
    }

    // @@protoc_insertion_point(class_scope:com.alimin.fk.pb.FkValueMap)
    private static final com.alimin.fk.pb.FkValueMapOuterClass.FkValueMap DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.alimin.fk.pb.FkValueMapOuterClass.FkValueMap();
    }

    public static com.alimin.fk.pb.FkValueMapOuterClass.FkValueMap getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FkValueMap>
        PARSER = new com.google.protobuf.AbstractParser<FkValueMap>() {
      @java.lang.Override
      public FkValueMap parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FkValueMap(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FkValueMap> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FkValueMap> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.alimin.fk.pb.FkValueMapOuterClass.FkValueMap getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alimin_fk_pb_FkValueMap_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alimin_fk_pb_FkValueMap_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alimin_fk_pb_FkValueMap_ValueEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alimin_fk_pb_FkValueMap_ValueEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020FkValueMap.proto\022\020com.alimin.fk.pb\032\017Fk" +
      "PbValue.proto\"\217\001\n\nFkValueMap\0226\n\005value\030\001 " +
      "\003(\0132\'.com.alimin.fk.pb.FkValueMap.ValueE" +
      "ntry\032I\n\nValueEntry\022\013\n\003key\030\001 \001(\t\022*\n\005value" +
      "\030\002 \001(\0132\033.com.alimin.fk.pb.FkPbValue:\0028\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.alimin.fk.pb.FkPbValueOuterClass.getDescriptor(),
        });
    internal_static_com_alimin_fk_pb_FkValueMap_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_alimin_fk_pb_FkValueMap_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alimin_fk_pb_FkValueMap_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_com_alimin_fk_pb_FkValueMap_ValueEntry_descriptor =
      internal_static_com_alimin_fk_pb_FkValueMap_descriptor.getNestedTypes().get(0);
    internal_static_com_alimin_fk_pb_FkValueMap_ValueEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alimin_fk_pb_FkValueMap_ValueEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.alimin.fk.pb.FkPbValueOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
